version: '3'

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
      
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stocksdb


